server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      teste: teste
    consumer:
      group-id: orcherstrator-group
      # sempre processar a partir do ultimo evento
      auto-offset-reset: latest

# desabilita o log do kafka
logging:
  level:
    org:
      apache:
        kafka: OFF