server:
  port: 8090

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      product-validation-success: product-validation-success
      product-validation-fail: product-validation-fail
    consumer:
      group-id: product-validation-group
      # sempre processar a partir do ultimo evento
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# desabilita o log do kafka
logging:
  level:
    org:
      apache:
        kafka: OFF